package config

// ConfigKeyHelp documents top-level JSON keys for operators (mel config keys).
var ConfigKeyHelp = map[string]string{
	"bind.api":                                       "HTTP listen address for API and web UI (host:port).",
	"bind.metrics":                                   "Reserved; metrics are served on bind.api when enabled.",
	"bind.allow_remote":                              "When true, API may listen on non-loopback (requires auth unless allow_insecure_remote).",
	"auth.enabled":                                   "Enable session auth for remote/UI access.",
	"auth.session_secret":                            "Secret for signing sessions; must be strong when auth is enabled.",
	"auth.ui_user":                                   "Dashboard username when auth is enabled.",
	"auth.ui_password":                               "Dashboard password when auth is enabled.",
	"auth.ui_password_hash":                          "bcrypt hash for dashboard password (preferred over plaintext ui_password).",
	"auth.allow_insecure_remote":                     "Development-only escape hatch for remote bind without auth.",
	"storage.data_dir":                               "Directory for SQLite parent path and runtime files.",
	"storage.database_path":                          "Path to the SQLite database file.",
	"storage.encryption_key_env":                     "Name of env var holding a 32-byte key when encryption_required is used.",
	"storage.encryption_required":                    "Fails startup unless the named env key is present (guard for at-rest plans).",
	"logging.level":                                  "debug|info|warning|error.",
	"logging.format":                                 "json|text style for stdout logs.",
	"retention.enabled":                              "Whether background retention jobs run.",
	"retention.messages_days":                        "TTL for stored mesh messages.",
	"retention.telemetry_days":                       "TTL for telemetry samples.",
	"retention.audit_days":                           "TTL for audit log rows.",
	"retention.precise_position_days":                "TTL for precise position fields when stored.",
	"privacy.store_precise_positions":                "Whether to persist precise coordinates.",
	"privacy.mqtt_encryption_required":               "Require TLS for MQTT broker connections.",
	"privacy.map_reporting_allowed":                  "Allow map-oriented reporting paths.",
	"privacy.redact_exports":                         "Redact sensitive fields in CLI/API exports.",
	"privacy.trust_list":                             "Optional explicit trust identifiers for policy layers.",
	"transports":                                     "Array of transport definitions (serial|tcp|mqtt|serialtcp).",
	"features.web_ui":                                "Serve the operator web dashboard.",
	"features.metrics":                               "Expose Prometheus metrics on the API listener.",
	"features.ble_experimental":                      "BLE remains unsupported in RC; flag is explicit only.",
	"features.google_maps_in_topology_ui":            "Optional Google Maps basemap on Topology when map reporting is allowed (third-party network).",
	"features.google_maps_api_key_env":               "Env var name holding Google Maps JavaScript API key (never put the key in JSON).",
	"rate_limits.http_rps":                           "HTTP request rate limit per client window.",
	"rate_limits.transport_reconnect_seconds":        "Minimum delay between transport reconnect attempts.",
	"intelligence":                                   "Transport intelligence query windows and scoring knobs.",
	"control.mode":                                   "disabled | advisory | guarded_auto.",
	"control.emergency_disable":                      "Hard stop for automated control actions.",
	"control.allowed_actions":                        "Action types the control plane may propose or execute.",
	"control.max_actions_per_window":                 "Cap on actions per rolling window.",
	"control.cooldown_per_target_seconds":            "Per-target cooldown between similar actions.",
	"control.require_min_confidence":                 "Minimum model confidence for non-advisory paths.",
	"control.allow_mesh_level_actions":               "Whether mesh-wide actions are permitted.",
	"control.allow_transport_restart":                "Whether automatic transport restart is allowed.",
	"control.allow_source_suppression":               "Whether noisy source suppression is allowed.",
	"control.action_window_seconds":                  "Rolling window for action budgeting.",
	"control.restart_cap_per_window":                 "Max transport restarts per window.",
	"control.max_queue":                              "Maximum queued control actions.",
	"control.action_timeout_seconds":                 "Timeout for action execution attempts.",
	"control.retention_days":                         "Retention for control-plane records.",
	"control.require_approval_for_action_types":      "Action types that always need human approval.",
	"control.require_approval_for_high_blast_radius": "Force approval for mesh/global blast radius.",
	"control.approval_timeout_seconds":               "Auto-expire pending approvals (0 = disabled).",
	"federation":                                     "Distributed kernel / peer federation settings.",
	"integration.enabled":                            "Enable outbound integration notifications.",
	"integration.alerts":                             "Forward transport alert events.",
	"integration.actions":                            "Forward control action lifecycle events.",
	"integration.state_changes":                      "Forward coarse transport state transitions.",
	"integration.anomalies":                          "Forward anomaly summaries when detected.",
	"integration.min_interval_seconds":               "Minimum seconds between posts to the same sink.",
	"integration.webhook_urls":                       "HTTPS URLs that receive JSON integration.Event payloads.",
	"integration.slack_webhook_url":                  "Slack incoming webhook URL.",
	"integration.telegram_bot_token_env":             "Env var name holding Telegram bot token (never put token in JSON).",
	"integration.telegram_chat_id":                   "Telegram chat id for sendMessage.",
	"scope.site_id":                                  "Optional stable site identifier for this MEL deployment (operator-chosen).",
	"scope.fleet_id":                                 "Optional fleet grouping id for related sites (does not enable federation).",
	"scope.fleet_label":                              "Optional human-readable fleet label for panels and exports.",
	"scope.gateway_label":                            "Optional label for this gateway among co-located observers.",
	"scope.expected_fleet_reporter_count":            "Expected MEL instances in a fleet view; values >1 surface partial-fleet visibility.",
	"strict_mode":                                    "When true, reject configs that violate safe-default posture.",
	"production_deploy":                              "When true, mel serve requires strict safe-default posture and at least one enabled transport.",
}
